### ISSUE TITLE
How to run gobit application?

### ISSUE THREAD

**Issue by monstercoder0** [infl00p/gobit#1]
I did try to run on windows 7 in visual code but I couldn't run it. Please give me a guide for a run this application.

[Running] go run "c:\Users\...\Desktop\gobit-main\main.go"
# command-line-arguments
.\main.go:240:14: undefined: InitLiveFeed
.\main.go:257:6: undefined: DisplaySubscribeModal
.\main.go:261:4: undefined: DisplaySubscribeInputForm
.\main.go:263:4: undefined: DisplayHelpModal
.\main.go:265:4: undefined: DisplayHelpModal
.\main.go:271:14: undefined: InitTrendBar
.\main.go:274:19: undefined: InitMomentumTable
.\main.go:277:18: undefined: InitDetailsTable
.\main.go:282:3: undefined: UpdateDetailTable
.\main.go:304:18: undefined: InitDb
.\main.go:304:18: too many errors

[Done] exited with code=2 in 1.143 seconds

**Comment by infl00p** [comment]
Hi @monstercoder0 ,
I have only verified it to work on linux and I don't have a windows environment right now, but I'll try to test it and make a build available for download in the next days.

But please, first check that you have go version 1.16 or later.

Thank you for your feedback

**Comment by monstercoder0** [comment]
Ok! Thank you for helping ;) 
First I'm not a developer, but I'll learn it soon specifically for Binance API.

Now, I have installed the go1.17.1 version and Visual Studio Code 1.60.0 version.

Can I run gobit in Visual Studio Code using Code Runner and Go Plugin?

**Comment by infl00p** [comment]
Hi @monstercoder0 
Although the Binance API is publicly documented at https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams
it does not include this specific websocket endpoint. Also I noticed that often it gets crippled. There is a forum post at https://dev.binance.vision/t/api-for-top-movers-or-large-sell-buy-data/1563 where I provide some more information.

Regarding the VSCode, I really can't help you, since I don't have any experience with it. You should be able to build in windows with the "go build" command, but you need a terminal application to run the binary, something like conemu or Windows 10 Terminal should be ok.

**Comment by monstercoder0** [comment]
Ok! is it really, Can I run gobit on conemu terminal? If yes! pls, leave guidance to run, or else pls leave a reply for close with this issue.
